### ISSUE TITLE
Thank you! I used CapMetrics in a demo at Google Cloud Next 2017

### ISSUE THREAD

**Issue by tswast** [scascketta/CapMetrics#2]
Hey @scascketta I want publicly thank you for making this dataset available. I used the CapMetrics BigQuery dataset you uploaded in [a demo visualizing the Austin public transit data](https://www.youtube.com/watch?v=t95-3Mwi328&feature=youtu.be&t=14m55s) in my talk at Google Cloud Next 2017.

Feel free to close this issue.

**Comment by tswast** [comment]
I also annotated and uploaded the [Jupyter notebook for the taco-transit demo](http://nbviewer.jupyter.org/github/tswast/code-snippets/blob/master/2017/austin-taco-transit/austin-taco-transit.ipynb).

**Comment by scascketta** [comment]
Wow, very cool! I love the demo you made and the notebook is great 💯
